databases:
  - name: smartalarmdb
    plan: free
    databaseName: smart_alarm_db
    user: smartalarm

services:
  - type: web
    plan: free
    name: smartalarmapi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: smartalarmdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4