# Generated by Django 5.1.2 on 2024-10-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm_settings',
            name='message',
        ),
        migrations.AddField(
            model_name='alarm_settings',
            name='mood',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alarm_settings',
            name='preferred_wake_method',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alarm_settings',
            name='schedule_importance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alarm_settings',
            name='sleep_quality',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alarm_settings',
            name='weather',
            field=models.IntegerField(null=True),
        ),
    ]
