# Generated by Django 5.1.2 on 2024-11-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_remove_alarm_settings_message_alarm_settings_mood_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Static_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('bed_quality', models.IntegerField(null=True)),
                ('ambient_noise', models.IntegerField(null=True)),
            ],
        ),
    ]
