# Generated by Django 5.1.2 on 2024-11-28 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSettings',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('stress_level', models.IntegerField(null=True)),
                ('wind_speed', models.IntegerField(null=True)),
                ('temperature', models.IntegerField(null=True)),
                ('humidity', models.IntegerField(null=True)),
                ('last_night_sleep', models.IntegerField(null=True)),
                ('sleep_debt', models.IntegerField(null=True)),
                ('meetings', models.IntegerField(null=True)),
                ('urgent_tasks', models.IntegerField(null=True)),
                ('physical_well_being', models.IntegerField(null=True)),
                ('user_age', models.IntegerField(null=True)),
                ('preffered_wake_method', models.IntegerField(null=True)),
                ('bed_quality', models.IntegerField(null=True)),
                ('ambient_noise', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuzzyOuput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatigue_level_out', models.FloatField(null=True)),
                ('schedule_importance_out', models.FloatField(null=True)),
                ('sleep_quality_out', models.FloatField(null=True)),
                ('weather_out', models.FloatField(null=True)),
                ('wake_time_adjustment', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alarm_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuzzy_outputs', to='fuzzy.alarmsettings')),
            ],
        ),
    ]
