# Generated by Django 5.1.2 on 2024-11-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_quality', models.IntegerField(null=True)),
                ('schedule_importance', models.IntegerField(null=True)),
                ('mood', models.IntegerField(null=True)),
                ('weather', models.IntegerField(null=True)),
                ('preferred_wake_method', models.IntegerField(null=True)),
            ],
        ),
    ]
