# Generated by Django 5.1.2 on 2024-12-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuzzyouput',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='alarmsettings',
            name='sleep_debt',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
