# Generated by Django 5.1.2 on 2024-11-22 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSettings_old',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_quality', models.IntegerField(null=True)),
                ('schedule_importance', models.IntegerField(null=True)),
                ('mood', models.IntegerField(null=True)),
                ('weather', models.IntegerField(null=True)),
                ('preferred_wake_method', models.IntegerField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='alarmsettings',
            old_name='mood',
            new_name='ambient_noise',
        ),
        migrations.RenameField(
            model_name='alarmsettings',
            old_name='preferred_wake_method',
            new_name='bed_quality',
        ),
        migrations.RenameField(
            model_name='alarmsettings',
            old_name='schedule_importance',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='alarmsettings',
            old_name='sleep_quality',
            new_name='last_night_sleep',
        ),
        migrations.RenameField(
            model_name='alarmsettings',
            old_name='weather',
            new_name='meetings',
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='physical_well_being',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='preffered_wake_method',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='sleep_debt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='stress_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='urgent_tasks',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='user_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='wind_speed',
            field=models.IntegerField(null=True),
        ),
    ]
