# Generated by Django 5.1.2 on 2024-12-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy', '0002_alter_fuzzyouput_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmsettings',
            name='sleep_debt',
            field=models.IntegerField(default=0),
        ),
    ]
