# Generated by Django 5.1.2 on 2024-11-24 13:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy', '0002_alarmsettings_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmsettings',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
