# Generated by Django 5.1.2 on 2024-11-24 14:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy', '0003_alarmsettings_timestamp_alarmsettings_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmsettings',
            name='fatigue_level_out',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='schedule_importance_out',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='sleep_quality_out',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='weather_out',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='alarmsettings',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
