# Generated by Django 5.1.2 on 2024-11-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy', '0004_alarmsettings_fatigue_level_out_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlarmSettings_old',
        ),
        migrations.AddField(
            model_name='alarmsettings',
            name='wake_time_adjustment',
            field=models.FloatField(null=True),
        ),
    ]
