# Generated by Django 5.1.2 on 2024-11-27 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy', '0005_delete_alarmsettings_old_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmsettings',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
