# Generated by Django 5.1.2 on 2024-11-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuzzy', '0006_alter_alarmsettings_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmsettings',
            name='ambient_noise',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmsettings',
            name='bed_quality',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmsettings',
            name='humidity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmsettings',
            name='last_night_sleep',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmsettings',
            name='meetings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmsettings',
            name='physical_well_being',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmsettings',
            name='preffered_wake_method',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmsettings',
            name='sleep_debt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmsettings',
            name='stress_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmsettings',
            name='temperature',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmsettings',
            name='urgent_tasks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmsettings',
            name='user_age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alarmsettings',
            name='wind_speed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
